### ISSUE TITLE
Is it possible to ignore security certificate error?

### ISSUE THREAD

**Issue by danielabar** [jeffbski/bench-rest#15]
Is it possible to tell bench-rest to ignore server security certificate errors?
For example, to pass `strictSSL : false` to the request options?

**Comment by jeffbski** [comment]
yes, you can include properties that mikeal/request allows for tuning your requests. I pass through all the properties. 

https://github.com/request/request

strictSSL - If true, requires SSL certificates be valid. 

So if you add `strictSSL: false` it should do just what you want.

**Comment by danielabar** [comment]
Thank you very much for quick response. Where would I specify the property? I tried adding it to `runOptions` but didn't seem to have any effect:

```
var benchrest = require('bench-rest');
var flow = 'https://some.api.with.self.signed.cert';

module.exports = flow;

var runOptions = {
  limit: 10,      // concurrent connections
  iterations: 20,  // number of iterations to perform
  strictSSL : false 
};

benchrest(flow, runOptions)
 .on('error', function (err, ctxName) { console.error('Failed in %s with err: ', ctxName, err); })
 .on('end', function (stats, errorCount) {
   console.log('error count: ', errorCount);
   console.log('stats', stats);
 });
```

The output shows error for each request like this:

```
Failed in main with err:  { [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

**Comment by jeffbski** [comment]
Try using the object style for flow definition which allows you to specify properties for each request.

```javascript
var flow = {
    main: [
      { get: 'http://localhost:8000/foo', strictSSL: false }
    ]
};
```

Each object in the main array is passed to request so you can add any additional options to each.

**Comment by danielabar** [comment]
That works. Thank you so much for your help!

**Comment by jeffbski** [comment]
Awesome! I'm glad I was able to help. Have a great day.
