### ISSUE TITLE
Update request module to support time property

### ISSUE THREAD

**Issue by Greg-GB** [jeffbski/bench-rest#18]
Update request module to support the time property. This will allow users to specify time in the all.requestOptions.

https://www.npmjs.com/package/request
version: 2.65.0 

time - If true, the request-response cycle (including all redirects) is timed at millisecond resolution, and the result provided on the response's elapsedTime property.

**Comment by jeffbski** [comment]
I have updated request to 2.65.0 and many other packages in the process. 

This is available in bench-rest@1.1.1 which I just published.
