### ISSUE TITLE
How to use with invalid https certificate?

### ISSUE THREAD

**Issue by keul** [jeffbski/bench-rest#34]
There's a way to obtain a sort of `--insecure` mode where self-signed https certificate are ignored?

**Comment by jeffbski** [comment]
Currently you would just add this as an option along with the url. It will take all the options that the `request` package supports like strictSSL. https://github.com/request/request

strictSSL - If true, requires SSL certificates be valid.

So if you add strictSSL: false it should do just what you want.

```js
var flow = {
    main: [
      { get: 'https://localhost:8000/foo', strictSSL: false }
    ]
};
```

**Comment by keul** [comment]
Thanks! It works perfectly!

**Comment by jeffbski** [comment]
excellent!
